#!/usr/bin/env bash

 
OSAF_VERMOUTH=/home/hieupham/Documents/OpenSAF_VERMOUTH
 

osaf_build_om()
{
	mkdir -p $OSAF_VERMOUTH/samples/immOm/build/
	cd $OSAF_VERMOUTH/samples/immOm/build
	cmake $OSAF_VERMOUTH/samples/immOm/
	make -C $OSAF_VERMOUTH/samples/immOm/build/
	echo "Stop cluster"
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	cp -u $OSAF_VERMOUTH/samples/immOm/bin/immOm /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/ 
	cp -u $OSAF_VERMOUTH/samples/immOm/bin/immOm /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/
	echo "Copied binary"
	echo "Starting cluster"
	bash $OSAF_VERMOUTH/lxc_osaf start
	sleep 10
	echo "Completed"
}
osaf_clean_om()
{
	rm -rf $OSAF_VERMOUTH/samples/immOm/bin
	rm -rf $OSAF_VERMOUTH/samples/immOm/build
	rm -rf $OSAF_VERMOUTH/samples/immOm/CMakeFiles
	rm -f $OSAF_VERMOUTH/samples/immOm/CMakeCache.txt
	rm -f $OSAF_VERMOUTH/samples/immOm/cmake_install.cmake
	rm -f $OSAF_VERMOUTH/samples/immOm/Makefile
}
osaf_build_oi()
{
	mkdir -p $OSAF_VERMOUTH/samples/immOi/build/
	cd $OSAF_VERMOUTH/samples/immOi/build
	cmake $OSAF_VERMOUTH/samples/immOi/
	make -C $OSAF_VERMOUTH/samples/immOi/build/
	echo "Stop cluster"
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop	
	cp -u $OSAF_VERMOUTH/samples/immOi/bin/immOi /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/ 
	cp -u $OSAF_VERMOUTH/samples/immOi/bin/immOi /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/
	echo "Copied binary"
	echo "Starting cluster"
	bash $OSAF_VERMOUTH/lxc_osaf start
	sleep 10
	echo "Completed"
}
osaf_clean_oi()
{
	rm -rf $OSAF_VERMOUTH/samples/immOi/bin
	rm -rf $OSAF_VERMOUTH/samples/immOi/build
	rm -rf $OSAF_VERMOUTH/samples/immOi/CMakeFiles
	rm -f $OSAF_VERMOUTH/samples/immOi/CMakeCache.txt
	rm -f $OSAF_VERMOUTH/samples/immOi/cmake_install.cmake
	rm -f $OSAF_VERMOUTH/samples/immOi/Makefile
}
osaf_build_amf()
{
	mkdir -p $OSAF_VERMOUTH/samples/amf/build/
	cd $OSAF_VERMOUTH/samples/amf/build
	cmake $OSAF_VERMOUTH/samples/amf/
	make -C $OSAF_VERMOUTH/samples/amf/build/
	echo "Stop cluster"
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop	
	cp -u $OSAF_VERMOUTH/samples/amf/bin/amf /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/amf_demo
	cp -u $OSAF_VERMOUTH/samples/amf/bin/amf /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/amf_demo
	echo "Copied binary"
	echo "Starting cluster"
	bash $OSAF_VERMOUTH/lxc_osaf start
	sleep 5
	
	echo "Completed"
}
osaf_clean_amf()
{
	rm -rf $OSAF_VERMOUTH/samples/amf/bin
	rm -rf $OSAF_VERMOUTH/samples/amf/build
	rm -rf $OSAF_VERMOUTH/samples/amf/CMakeFiles
	rm -f $OSAF_VERMOUTH/samples/amf/CMakeCache.txt
	rm -f $OSAF_VERMOUTH/samples/amf/cmake_install.cmake
	rm -f $OSAF_VERMOUTH/samples/amf/Makefile
}
osaf_build_server()
{
	mkdir -p $OSAF_VERMOUTH/server/build/
	cd $OSAF_VERMOUTH/server/build
	cmake $OSAF_VERMOUTH/server/
	make -C $OSAF_VERMOUTH/server/build/
	echo "Stop cluster"
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop
	sleep 5
	bash $OSAF_VERMOUTH/lxc_osaf stop	
	cp -u $OSAF_VERMOUTH/server/bin/server /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/amf_demo
	cp -u $OSAF_VERMOUTH/server/bin/server /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/amf_demo
	echo "Copied binary"
	echo "Starting cluster"
	bash $OSAF_VERMOUTH/lxc_osaf start
	sleep 5
	
	echo "Completed"
}
osaf_clean_server()
{
	rm -rf $OSAF_VERMOUTH/server/bin
	rm -rf $OSAF_VERMOUTH/server/build
	rm -rf $OSAF_VERMOUTH/server/CMakeFiles
	rm -f $OSAF_VERMOUTH/server/CMakeCache.txt
	rm -f $OSAF_VERMOUTH/server/cmake_install.cmake
	rm -f $OSAF_VERMOUTH/server/Makefile
}
osaf_config_PL()
{
	mkdir -p /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/
	cp -u $OSAF_VERMOUTH/samples/amf/amf_demo_script /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/
	cp -u $OSAF_VERMOUTH/samples/amf/AppConfig-2N.xml /var/lib/lxc/LXC_OSAF_3/rootfs/opt/amf_demo/
	lxc-attach -n LXC_OSAF_3 -- immcfg -f /opt/amf_demo/AppConfig-2N.xml
	lxc-attach -n LXC_OSAF_3 -- amf-adm unlock-in safSu=SU1,safSg=AmfDemo,safApp=AmfDemo1
	lxc-attach -n LXC_OSAF_3 -- amf-adm unlock safSu=SU1,safSg=AmfDemo,safApp=AmfDemo1
	echo "Configure Playload 3 completed"	
	mkdir -p /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/
	cp -u $OSAF_VERMOUTH/samples/amf/amf_demo_script /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/
	cp -u $OSAF_VERMOUTH/samples/amf/AppConfig-2N.xml /var/lib/lxc/LXC_OSAF_4/rootfs/opt/amf_demo/
	lxc-attach -n LXC_OSAF_4 -- immcfg -f /opt/amf_demo/AppConfig-2N.xml
	lxc-attach -n LXC_OSAF_4 -- amf-adm unlock-in safSu=SU2,safSg=AmfDemo,safApp=AmfDemo1
	lxc-attach -n LXC_OSAF_4 -- amf-adm unlock safSu=SU2,safSg=AmfDemo,safApp=AmfDemo1
	echo "Configure Playload 4 completed"
}
osaf_tail_log3()
{
	lxc-attach -n LXC_OSAF_3 -- tailf /var/log/syslog
}
osaf_tail_log4()
{
	lxc-attach -n LXC_OSAF_4 -- tailf /var/log/syslog
}
osaf_cat_log3()
{
	lxc-attach -n LXC_OSAF_3 -- cat /var/log/syslog
}
osaf_cat_log4()
{
	lxc-attach -n LXC_OSAF_4 -- cat /var/log/syslog
}
osaf_switch_over()
{
	lxc-attach -n LXC_OSAF_4 -- amf-adm si-swap safSi=AmfDemo,safApp=AmfDemo1
}
osaf_fail_over_PL3()
{
	bash $OSAF_VERMOUTH/lxc_osaf stop 3
	sleep 10 &
	bash $OSAF_VERMOUTH/lxc_osaf start 3
}
osaf_fail_over_PL4()
{
	bash $OSAF_VERMOUTH/lxc_osaf stop 4
	sleep 10 &
	bash $OSAF_VERMOUTH/lxc_osaf start 4
}
osaf_show_if_PL3()
{
	lxc-attach -n LXC_OSAF_3 -- ifconfig
}
osaf_show_if_PL4()
{
	lxc-attach -n LXC_OSAF_4 -- ifconfig
}
osaf_run_OM()
{
	lxc-attach -n LXC_OSAF_3 -- /opt/amf_demo/immOm
}
osaf_run_OI()
{
	lxc-attach -n LXC_OSAF_3 -- /opt/amf_demo/immOi 
}
osaf_help()
{
	    echo "Command list:
	buildOi
	buildOm
	buildAmf
	buildServer
	cleanOi
	cleanOm
	cleanAmf
	cleanServer
	showRoute
	setRoute
	delRoute
	setInterfaces
	configPLs
	catLogPL3
	catLogPL4
	tailLogPL3
	tailLogPL4
	switchOver
	failOverPL3
	failOverPL4
	showIfPL3
	showIfPL4
"
}
osaf_set_route()
{
	sysctl net.ipv4.ip_forward=1;
	iptables -t nat -A PREROUTING -p tcp -d 192.168.122.239 --dport 8888 -j DNAT --to-destination 10.0.3.105:8888;
	iptables -t nat -A POSTROUTING -j MASQUERADE
}
osaf_del_route()
{
	sysctl net.ipv4.ip_forward=0;
	iptables -t nat -D PREROUTING -p tcp -d 192.168.122.239 --dport 8888 -j DNAT --to-destination 10.0.3.105:8888;
	iptables -t nat -D POSTROUTING -j MASQUERADE
}
osaf_set_interfaces()
{
	sudo apt-get install virtualbox-guest-additions-iso
	cp -u $OSAF_VERMOUTH/interfaces /etc/network/

	echo "
	Shutdown Virtual Box
	Config Network in Virtual Box, add these settings

	Adapter 1 Nat
	Adapter 2 Host-only
	Adapter 3 Bridge adapter

"
}
osaf_show_route()
{
iptables -L -v -n --line-numbers -t nat
}
while test ${#} -gt 0; do
    case "$1" in
        buildOi)
            osaf_build_oi
            ;;
		buildOm)
            osaf_build_om
            ;;
		buildAmf)
            osaf_build_amf
            ;;
		buildServer)
            osaf_build_server
            ;;
        help)
            osaf_help
            ;;
		setRoute)
			osaf_set_route
			;;
		setInterfaces)
			osaf_set_interfaces
			;;
		showRoute)
			osaf_show_route
			;;
		delRoute)
			osaf_del_route
			;;
		cleanOi)
			osaf_clean_oi
			;;
		cleanOm)
			osaf_clean_om
			;;
		cleanAmf)
			osaf_clean_amf
			;;
		cleanServer)
			osaf_clean_server
			;;
		tailLogPL3)
			osaf_tail_log3
			;;
		tailLogPL4)
			osaf_tail_log4
			;;
		catLogPL3)
			osaf_cat_log3
			;;
		catLogPL4)
			osaf_cat_log4
			;;
		configPLs)
			osaf_config_PL
			;;
		switchOver)
			osaf_switch_over
			;;
		failOverPL3)
			osaf_fail_over_PL3
			;;
		failOverPL4)
			osaf_fail_over_PL4
			;;	
		showIfPL3)
			osaf_show_if_PL3
			;;	
		showIfPL4)
			osaf_show_if_PL4
			;;	
		runOm)
			osaf_run_OM
			;;
		runOi)
			osaf_run_OI
			;;
        *)
            echo "Unknown command: $1"
            osaf_help
            exit 1
    esac
    shift
done

exit 0
