/*
 
*Function : ClientGUI
*Description: Client Interfaces. Chat General or Select User to Private Chat
*Argument: Nope!
*Return: Nope!
Note: First Interface 

 */
package chatclient;
import java.awt.ComponentOrientation;
import java.awt.Container;

import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;

import javax.swing.JButton;

import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author hieupham
 */

public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    Global g = Global.getInstance();
    Thread waitThr;
    //Thread MessThr;
    private String sName;
    private DefaultListModel listModel,listModelUserPrv;
    RoomGUI roomNew;
    
    public ClientGUI() {
        initComponents();
        listRoom.setModel(new DefaultListModel());
        listModel = new DefaultListModel();
        listUserPrv.setModel(new DefaultListModel());
        listModelUserPrv = new DefaultListModel();
        
        //User cannot change
        txtContent.setEditable(false);
        txtContent.setCaretPosition(0);
        
        waitThr = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    try {
                        if (g.client.GetCommandCode() == g.client.ADDOK){
                            int mcServer = JOptionPane.INFORMATION_MESSAGE;
                            JOptionPane.showMessageDialog (null, "Got", "Warning", mcServer);
                            g.client.ClearData();
                            //waitThr.stop();
                        }
                        else if (g.client.GetCommandCode() == g.client.PRVOK){
                            //int mcServer = JOptionPane.INFORMATION_MESSAGE;
                            //JOptionPane.showMessageDialog (null, "PRV", "Warning", mcServer);
                            g.client.ClearData();
                            //waitThr.stop();
                        }
                        else if (g.client.GetCommandCode() == g.client.RECVPRV){
                            //int mcServer = JOptionPane.INFORMATION_MESSAGE;
                            //JOptionPane.showMessageDialog (null,"PRV " + g.client.GetName() + g.client.GetMessage(), "Warning", mcServer);
                            if (listUserPrv.getSelectedValue().contains(g.client.GetName())){
                                txtContent.append(g.client.GetName() + ": " + g.client.GetMessage() + "\n");
                            }
                            g.client.ClearData();
                        }
                        else if (g.client.GetCommandCode() == g.client.ADDROOMOK){
                            roomNew = new RoomGUI(sName);           
                            roomNew.setVisible(true);
                            listModel.addElement(sName);
                            if(true){
           
                                listRoom.setModel(listModel);
                                sName = "";
                            }
                            g.client.ClearData();
                        }
                    } catch (Exception e) {
                    }
                }
            }
        });
        
        if (!waitThr.isAlive())
            waitThr.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtChat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbRoom1 = new javax.swing.JLabel();
        lbRoom2 = new javax.swing.JLabel();
        btnCreateRoom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRoom = new javax.swing.JList<>();
        addUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUserPrv = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Room Avaiable");

        txtChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChatKeyPressed(evt);
            }
        });

        jLabel2.setText("User Avaiable");

        lbRoom1.setText("Room N1");
        lbRoom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRoom1MouseClicked(evt);
            }
        });

        lbRoom2.setText("Room N2");
        lbRoom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRoom2MouseClicked(evt);
            }
        });

        btnCreateRoom.setText("CreateRoom");
        btnCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoomActionPerformed(evt);
            }
        });

        listRoom.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listRoomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listRoom);

        addUser.setText("AddUser");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        listUserPrv.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listUserPrv.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listUserPrvValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listUserPrv);

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane3.setViewportView(txtContent);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbRoom1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbRoom2)
                                            .addComponent(btnCreateRoom))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(addUser))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(385, Short.MAX_VALUE)
                        .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbRoom1)
                                .addGap(11, 11, 11)
                                .addComponent(lbRoom2)
                                .addGap(4, 4, 4)
                                .addComponent(btnCreateRoom)
                                .addGap(77, 77, 77)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUser))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbRoom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoom1MouseClicked
        // TODO add your handling code here:
        //g.client.AddFriend("zzz");
        //g.client.SendPrivateMessage("fxanhkhoa", "gogogo");
        //if (!waitThr.isAlive())
            //waitThr.start();
        JPanel pnBox=new JPanel();
        if(evt.getClickCount() % 2 == 0)
        {
            // Open Function Room
            
            RoomGUI room1 = new RoomGUI("Room1");
           
           room1.setVisible(true);
            listModel.addElement("Room1");
        if(true)
        {
           
           listRoom.setModel(listModel);
            
        }
            //
        }
    }//GEN-LAST:event_lbRoom1MouseClicked

    private void lbRoom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoom2MouseClicked
        // TODO add your handling code here:

        if(evt.getClickCount() % 2 == 0)
        {
            // Open Function Room
            RoomGUI room2 = new RoomGUI("Room2");           
            room2.setVisible(true);
            listModel.addElement("Room2");
        if(true)
        {
           
           listRoom.setModel(listModel);
            
        }
             
            System.out.println("Double click !!");
            
            //
        }
    }//GEN-LAST:event_lbRoom2MouseClicked

    private void txtChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChatKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if (!listUserPrv.isSelectionEmpty()){
                txtContent.append(txtChat.getText() + "\n");
                g.client.SendPrivateMessage(listUserPrv.getSelectedValue(), txtChat.getText());
                //System.out.println("SEND ");
                txtChat.setText("");
            }
            else{
                int mcServer = JOptionPane.ERROR_MESSAGE;
                JOptionPane.showMessageDialog (null, "Select 1 user man!!!!", "Warning", mcServer);
            }
        }
    }//GEN-LAST:event_txtChatKeyPressed

    private void btnCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoomActionPerformed
        // TODO add your handling code here:
        int mc = JOptionPane.INFORMATION_MESSAGE;
	sName = JOptionPane.showInputDialog (null, "Type Room's Name", "Create Room to Chat Private", mc);
        g.client.AddNewRoom(sName);             
    }//GEN-LAST:event_btnCreateRoomActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here:
        int mc = JOptionPane.INFORMATION_MESSAGE;
	sName = JOptionPane.showInputDialog (null, "Type User", "Create Room to Chat Private", mc);
        g.client.AddFriend(sName);
        listModelUserPrv.addElement(sName);
        if(true)
        {
           
           listUserPrv.setModel(listModelUserPrv);
           sName = "";
        }
    }//GEN-LAST:event_addUserActionPerformed

    private void listRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRoomMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2){
            //Double-click detected
            int index = listRoom.locationToIndex(evt.getPoint());
            RoomGUI roomNew = new RoomGUI(listRoom.getSelectedValue());           
            roomNew.setVisible(true);
        }
    }//GEN-LAST:event_listRoomMouseClicked

    private void listUserPrvValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listUserPrvValueChanged
        // TODO add your handling code here:
        JList changedList = (JList)evt.getSource();
        if (listUserPrv == changedList){
            System.out.println("gogogo");
            txtContent.setText("");
        }
    }//GEN-LAST:event_listUserPrvValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JButton btnCreateRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbRoom1;
    private javax.swing.JLabel lbRoom2;
    private javax.swing.JList<String> listRoom;
    private javax.swing.JList<String> listUserPrv;
    private javax.swing.JTextField txtChat;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
