/*
 
*Function : MainGUI
*Description: Main Interfaces. Login to Chat Server or Sign Up Account.
*Argument: Nope!
*Return: Nope!
Note: First Interface 

 */
package chatclient;

import javax.swing.*;
import javax.xml.ws.spi.Invoker;

/**
 *
 * @author hieupham
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public String sUser,sPass;
    Global g ;
    SavedPreference sP;
    Thread waitthr;
    ProtocolCS p ;
    
    public MainGUI() {
        initComponents();
        
        //Variables
        g = Global.removeInstance();
        g = Global.getInstance();
        sP = SavedPreference.getInstance();
        p = new ProtocolCS();
        
        //UI
        reconnectButton.setEnabled(false);
        
        //Thread Processing
        waitthr = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            while (true){
                                try{
                                    if (g.client.IsDataReceived() == 1){
                                        btnSignIn.setEnabled(true);
                                        
                                    }
                                    if (g.client.GetStatus() == true){
                                        reconnectButton.setEnabled(false);
                                        btnSignIn.setEnabled(true);
                                        btnSignUp.setEnabled(true);
                                        txtUser.setEnabled(true);
                                        txtPassF.setEnabled(true);
                                    }
                                    if (g.client.GetCommandCode() == g.client.SIGNINOK){
                                        //int mcServer = JOptionPane.INFORMATION_MESSAGE;
                                        //JOptionPane.showMessageDialog (null, "Welcome", "Warning", mcServer);
                                        sP.SetUserName(txtUser.getText());
                                        sP.SetPass(txtPassF.getText());
                                        g.client.GetIDUser();
                                        g.client.ClearData();
                                        ClientGUI clientGui = new ClientGUI();
                                        clientGui.setVisible(true);
                                        while (!clientGui.isActive());
                                        MainGUI.this.dispose();
                                        System.out.println("Join to Client GUI");   
                                        waitthr.stop();
                                    }
                                    if (g.client.GetCommandCode() == g.client.SIGNINFAIL){
                                        int mc = JOptionPane.WARNING_MESSAGE;
                                        JOptionPane.showMessageDialog (null, "Sign In Fail", "Warning", mc);
                                        g.client.ClearData();
                                    }
                                }catch (Exception e){
                                    
                                }
                            }
                        }
                    });
        if (!waitthr.isAlive())
            waitthr.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassF = new javax.swing.JPasswordField();
        reconnectButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jQuit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        itemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel2.setText("Need an account? Register now!!!");

        jLabel1.setText("Powered by VERMOUNTH");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("WELCOME BACK");

        reconnectButton.setText("Reconnect");
        reconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconnectButtonActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        jQuit.setText("Quit");
        jQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuitActionPerformed(evt);
            }
        });
        menuFile.add(jQuit);

        jMenuBar1.add(menuFile);

        menuAbout.setText("About");

        itemAbout.setText("VERMOUTH");
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        menuAbout.add(itemAbout);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reconnectButton))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPassF, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(reconnectButton))
                        .addGap(18, 18, 18)))
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(txtPassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        
        sUser=txtUser.getText();
        //sPass=txtPass.getText();
        sPass=txtPassF.getText();
        
                // GET RESPONE SERVER
                if(g.client.GetStatus() == true)
                {           
                    if(sUser.equals("") )
                    {
                        int mc = JOptionPane.WARNING_MESSAGE;
                        JOptionPane.showMessageDialog (null, "Blank USER", "Warning", mc);
                    }
                    else if(sPass.equals("")){
                        int mc2 = JOptionPane.WARNING_MESSAGE;
                        JOptionPane.showMessageDialog (null, "Blank PASS", "Warning", mc2);
                    }
                    //if (g.client.StartReceive() == 1){
                    
                        g.client.SignIn(sUser, sPass);
                        //System.out.println("as");
                        
                        
                    btnSignIn.setEnabled(false);
                    //}
                }
                else
                {
//                   int mcServer = JOptionPane.ERROR_MESSAGE;
//                   JOptionPane.showMessageDialog (null, "Cann't connect to Server", "Warning", mcServer);
                   int reply= JOptionPane.showConfirmDialog( null,"Please check your internet and sign in again.\nCorrect? ", "Cann't connect to Server", JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
                   if(sP.max<2)
                   {
                        sP.max++;
                        if(reply==JOptionPane.YES_OPTION)
                        {
                            System.out.println("YES OPTION");
                            waitthr.stop();
                            g.client = null;
                            g.client = new Client();

                        }
                        
     //                   reconnectButton.setEnabled(true);
     //                   btnSignIn.setEnabled(false);
     //                   btnSignUp.setEnabled(false);
     //                   txtUser.setEnabled(false);
     //                   txtPassF.setEnabled(false);
                    }
                   else
                   {
                       sP.max=0;
                       System.exit(0);
                   }
                }

    }//GEN-LAST:event_btnSignInActionPerformed

    
    /* add function sign up  */
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        
        /* ADD FUCNTION SIGN UP */
        SignUpGUI signupGui = new SignUpGUI();
        signupGui.setVisible(true);
        MainGUI.this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        // TODO add your handling code here:
        int mcAbout = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog (null, "All for one target", "VERMOTH", mcAbout);
    }//GEN-LAST:event_itemAboutActionPerformed

    private void jQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jQuitActionPerformed

    private void reconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconnectButtonActionPerformed
        g.client = null;
        g.client = new Client();
    }//GEN-LAST:event_reconnectButtonActionPerformed
        /* END FUCNTION SIGN UP  */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
                //Global g = Global.getInstance();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jQuit;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuFile;
    private javax.swing.JButton reconnectButton;
    private javax.swing.JPasswordField txtPassF;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
