/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.xml.ws.spi.Invoker;


/**
 *
 * @author hieupham
 */
public class SignGUI extends javax.swing.JPanel {

    /**
     * Creates new form SignGUI
     */
    public String sUser,sPass;
    Global g ;
    Thread waitthr;
    ProtocolCS p ;
    public int connectStatus = 0;
    Client _Client;
    
    public SignGUI() {
        initComponents();
        _Client = Client.getInstance();
          _Client.InitVar();
        //UI
        btnReconnect.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassF = new javax.swing.JPasswordField();
        btnReconnect = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });

        jLabel5.setText("WELCOME BACK");

        txtPassF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassFKeyPressed(evt);
            }
        });

        btnReconnect.setText("Reconnect");
        btnReconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconnectActionPerformed(evt);
            }
        });

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel2.setText("Need an account? Register now!!!");

        jLabel1.setText("Powered by VERMOUNTH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReconnect))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPassF, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnReconnect))
                        .addGap(18, 18, 18)))
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(txtPassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            _Client=Client.getInstance();
            sUser=txtUser.getText();
            //sPass=txtPass.getText();
            sPass=txtPassF.getText();
            if(sUser.equals("") ){
                int mc = JOptionPane.ERROR_MESSAGE;
                JOptionPane.showMessageDialog (null,  "BLANK USER" ,"Sign In Fail", mc);
            }
            else if(sPass.equals("")){
                int mc = JOptionPane.ERROR_MESSAGE;
                JOptionPane.showMessageDialog (null, "BLANK PASS", "Sign In Fail", mc);
            }
            else{
                if(_Client.sP.statusConnect==1)
                {
                    _Client.SignIn(sUser, sPass);
                }
                else
                {
                    int mc = JOptionPane.ERROR_MESSAGE;
                    JOptionPane.showMessageDialog (null, "Sign In Fail", "Can not connect to Server", mc);
                }
            }
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPassFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassFKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            _Client=Client.getInstance();
            sUser=txtUser.getText();
            //sPass=txtPass.getText();
            sPass=txtPassF.getText();
            if(sUser.equals("") ){
                int mc = JOptionPane.ERROR_MESSAGE;
                JOptionPane.showMessageDialog (null,  "BLANK USER" ,"Sign In Fail", mc);
            }
            else if(sPass.equals("")){
                int mc = JOptionPane.ERROR_MESSAGE;
                JOptionPane.showMessageDialog (null, "BLANK PASS", "Sign In Fail", mc);
            }
            else{
                if(_Client.sP.statusConnect==1)
                {
                    _Client.SignIn(sUser, sPass);
                }
                else
                {
                    int mc = JOptionPane.ERROR_MESSAGE;
                    JOptionPane.showMessageDialog (null, "Sign In Fail", "Can not connect to Server", mc);
                }
            }
        }
    }//GEN-LAST:event_txtPassFKeyPressed

    private void btnReconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconnectActionPerformed
        try {
            btnReconnect.setEnabled(false);
            Thread.sleep(3000);
            _Client.ReconLog();
        } catch (InterruptedException ex) {        }
    }//GEN-LAST:event_btnReconnectActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        _Client=Client.getInstance();
        sUser=txtUser.getText();
        sPass=txtPassF.getText();
        if(sUser.equals("") ){
            int mc = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog (null,  "BLANK USER" ,"Sign In Fail", mc);
        }
        else if(sPass.equals("")){
            int mc = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog (null, "BLANK PASS", "Sign In Fail", mc);
        }
        else{
            if(_Client.sP.statusConnect==1)
            {
                _Client.SignIn(sUser, sPass);
            }
            else
            {
                int mc = JOptionPane.ERROR_MESSAGE;
                JOptionPane.showMessageDialog (null, "Sign In Fail", "Can not connect to Server", mc);
            }
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:

        /* ADD FUCNTION SIGN UP */
        SignUpGUI signupGui = new SignUpGUI();
        signupGui.setVisible(true);
        _Client.sP.mG.setVisible(false);
    }//GEN-LAST:event_btnSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReconnect;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassF;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
