/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author hieupham
 */
public class tChat extends javax.swing.JFrame {

    /**
     * Creates new form tChat
     */
    public StyledDocument doc ;
    public SimpleAttributeSet left,right;

    public tChat() {
        initComponents();
        doc= textPane.getStyledDocument();
        SimpleAttributeSet left = new SimpleAttributeSet();
        StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
        StyleConstants.setForeground(left, Color.RED);

        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        StyleConstants.setForeground(right, Color.BLUE);
//        try
//        {
//            doc.insertString(doc.getLength(), "LEFT FRIST", left );
//            doc.setParagraphAttributes(doc.getLength(), 1, left, false);
////            doc.insertString(doc.getLength(), "\nNo", right );
////            doc.setParagraphAttributes(doc.getLength(), 1, right, false);
//        }
//        catch(Exception e) { System.out.println(e); }
//        JFrame frame = new JFrame("Text Pane Chat");
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.add( new JScrollPane( textPane ) );
//        frame.setLocationByPlatform( true );
//        frame.setSize(200, 200);
//        frame.setVisible( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTextChat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTextChat.setText("ENTER");
        txtTextChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTextChatKeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(textPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTextChat, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTextChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTextChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextChatKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            
                // TODO add your handling code here:
                    String getText=txtTextChat.getText();
                    if(getText.equals("")){
                        return;
                    }
                    else{
                        SentSetAlign(getText);
                        RecvSetAlign("this String must be on right");
                        
//                            SimpleAttributeSet tleft = new SimpleAttributeSet();
//                            StyleConstants.setAlignment(tleft, StyleConstants.ALIGN_LEFT);
//                            StyleConstants.setForeground(tleft, Color.RED);
//
//                            SimpleAttributeSet tright = new SimpleAttributeSet();
//                            StyleConstants.setAlignment(tright, StyleConstants.ALIGN_RIGHT);
//                            StyleConstants.setForeground(tright, Color.BLUE);
//                    doc.setParagraphAttributes(doc.getLength(), 1, tleft, false);          
//                    doc.insertString(doc.getLength(), "Question ?\n", tleft );
//                    doc.setParagraphAttributes(doc.getLength(), 1, tleft, false);        
//                                            
//                        /**/
//                        doc.setParagraphAttributes(doc.getLength(), 1, tright, false);
//                        doc.insertString(doc.getLength(), getText+"\n", tright );
//                        doc.setParagraphAttributes(doc.getLength(), 1, tright, false);
                /**/
//                doc.insertString(doc.getLength(), "\nNo", tright );
//                doc.setParagraphAttributes(doc.getLength(), 1, tright, false);
//                doc.insertString(doc.getLength(), "\nFeel like going to a movie?", tleft );
//                doc.setParagraphAttributes(doc.getLength(), 1, tleft, false);
//                doc.insertString(doc.getLength(), "\nSure", tright );
//                doc.setParagraphAttributes(doc.getLength(), 1, tright, false);

                }
            
            
//            } catch (BadLocationException ex) {
//                Logger.getLogger(tChat.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_txtTextChatKeyPressed
public void SentSetAlign(String msg ){
        try {
            SimpleAttributeSet leftA = new SimpleAttributeSet();
            StyleConstants.setAlignment(leftA, StyleConstants.ALIGN_LEFT);
            StyleConstants.setForeground(leftA, Color.RED);
            doc.setParagraphAttributes(doc.getLength(), 1, leftA, false);
            doc.insertString(doc.getLength(), msg+"\n", leftA );
            doc.setParagraphAttributes(doc.getLength(), 1, leftA, false);
        } catch (BadLocationException ex) {
            Logger.getLogger(tChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public void RecvSetAlign(String msg){
        try {
            SimpleAttributeSet rightA = new SimpleAttributeSet();
            StyleConstants.setAlignment(rightA, StyleConstants.ALIGN_RIGHT);
            StyleConstants.setForeground(rightA, Color.BLUE);
            doc.setParagraphAttributes(doc.getLength(), 1, rightA, false);
            doc.insertString(doc.getLength(), msg+"\n", rightA );
            doc.setParagraphAttributes(doc.getLength(), 1, rightA, false);
        } catch (BadLocationException ex) {
            Logger.getLogger(tChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPane;
    private javax.swing.JTextField txtTextChat;
    // End of variables declaration//GEN-END:variables
}
