/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javachatclient;

import GUIPannel.BlackListPanel;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author ubuntu
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    /**/
     // multi input
    private JFrame frame;
    private JPanel pane;
    private JTextField nameROOMField,nameUserField;
    private JPasswordField passROOMField,passCURField,passNEWField;
    private String nameROOM="";
    private String passROOM="";
    //
    /**/
    public MainWindow() {
        initComps();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        GlobalStatic.getInstance();
        
        this.add(GlobalStatic.signupPannel);
        GlobalStatic.signupPannel.setVisible(true);
        
        this.add(GlobalStatic.signinPannel);
        GlobalStatic.signinPannel.setVisible(true);
        
        //this.add(new SignInPannel());
        
        this.pack();
        JFrame topFrame = (JFrame) SwingUtilities.getRootPane(GlobalStatic.signinPannel).getParent();
        //this.jMenuAccount.setVisible(false);
        this.jMenuAccount.setEnabled(false);
        
        topFrame.setLocationRelativeTo(null);
        
//            topFrame.setSize(1000,625);
    }
    
    private void initComps(){
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        FailServerByID = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemSignOut = new javax.swing.JMenuItem();
        jMenuItemChangePass = new javax.swing.JMenuItem();
        /**/
        jMenuBlackList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFile.setText("File");

        jExit.setText("Quit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jExit);

        jMenuBar1.add(jMenuFile);

        jMenu2.setText("Edit");

        FailServerByID.setText("Fail");
        FailServerByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FailServerByIDActionPerformed(evt);
            }
        });
        jMenu2.add(FailServerByID);

        jMenuBar1.add(jMenu2);

        jMenuAccount.setText("Account");

        jMenuItemSignOut.setText("Sign Out");
        jMenuItemSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSignOutActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemSignOut);

        jMenuItemChangePass.setText("Change Password");
        jMenuItemChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangePassActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemChangePass);
        /**/
        jMenuBlackList.setText("Black List");
        jMenuBlackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBlackListActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuBlackList);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPannel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        FailServerByID = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemSignOut = new javax.swing.JMenuItem();
        jMenuItemChangePass = new javax.swing.JMenuItem();
        jMenuBlackList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPannel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout MainPannelLayout = new javax.swing.GroupLayout(MainPannel);
        MainPannel.setLayout(MainPannelLayout);
        MainPannelLayout.setHorizontalGroup(
            MainPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MainPannelLayout.setVerticalGroup(
            MainPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");

        jExit.setText("Quit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jExit);

        jMenuBar1.add(jMenuFile);

        jMenu2.setText("Edit");

        FailServerByID.setText("Fail");
        FailServerByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FailServerByIDActionPerformed(evt);
            }
        });
        jMenu2.add(FailServerByID);

        jMenuBar1.add(jMenu2);

        jMenuAccount.setText("Account");

        jMenuItemSignOut.setText("Sign Out");
        jMenuItemSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSignOutActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemSignOut);

        jMenuItemChangePass.setText("Change Password");
        jMenuItemChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangePassActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemChangePass);

        jMenuBlackList.setText("Black List");
        jMenuBlackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBlackListActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuBlackList);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ShowAccountBar(){
        this.jMenuAccount.setEnabled(true);
    }
    public void HideAccountBar(){
        this.jMenuAccount.setEnabled(false);
    }
    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void FailServerByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FailServerByIDActionPerformed
        // TODO add your handling code here:
//        _Client.SendMsgToRoom(-1, "Fail");
    }//GEN-LAST:event_FailServerByIDActionPerformed

    private void jMenuItemSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSignOutActionPerformed
        // TODO add your handling code here:

        try {
            GlobalStatic.clientThread.SignOut();
//            Thread.sleep(ALLBITS);
            GlobalStatic.clientThread.GetCommandCode();
            //this.dispose();
        } catch (InterruptedException ex) {}

    }//GEN-LAST:event_jMenuItemSignOutActionPerformed

    private void jMenuItemChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangePassActionPerformed
        // TODO add your handling code here:
        //        int mcUser = JOptionPane.INFORMATION_MESSAGE;
        //        String sPassUser = JOptionPane.showInputDialog (null, "Type Password to change", "Chang password ", mcUser);
        //        _Client.RePass(sPassUser);
        {
            /*GET MULTI INPUT */
            pane = new JPanel();
            pane.setLayout(new GridLayout(0, 2, 2, 2));
            passCURField = new JPasswordField(29);
            passNEWField = new JPasswordField(29);
            pane.add(new JLabel("Fill current Password"));
            pane.add(passCURField);
            pane.add(new JLabel("Set NEW Password"));
            pane.add(passNEWField);

            int option = JOptionPane.showConfirmDialog(frame, pane, "Please FILL ALL", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (option == JOptionPane.OK_OPTION) {

                String passCUR = passCURField.getText();
                String passNEW = passNEWField.getText();
                if(passCUR.equals(GlobalStatic.myPass)){
                    GlobalStatic.clientThread.RePassUser(passNEW);
                }
                else{
                    int mcServer = JOptionPane.ERROR_MESSAGE;
                    JOptionPane.showMessageDialog (null, "PASSWORD NOT MATCH", "ERROR", mcServer);
                    System.err.println("NOT ACCESS ");
                }
            }
            else{
                System.err.println("Cancel action");
            }
        }
    }//GEN-LAST:event_jMenuItemChangePassActionPerformed

    private void jMenuBlackListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBlackListActionPerformed
        // TODO add your handling code here:
        pane = new BlackListPanel();
        int iNewFriend = JOptionPane.showConfirmDialog(frame, pane, " BLACK LIST USER: "+GlobalStatic.myUserName, JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(iNewFriend==JOptionPane.OK_OPTION){
            System.err.println("OK this action BLACKLIST");
        }
        else{
            System.err.println("Cancel this action BLACKLIST");
        }
    }//GEN-LAST:event_jMenuBlackListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FailServerByID;
    private javax.swing.JPanel MainPannel;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBlackList;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemChangePass;
    private javax.swing.JMenuItem jMenuItemSignOut;
    // End of variables declaration//GEN-END:variables
}
