/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPannel;

import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javachatclient.GlobalStatic;
import javachatclient.Struct.OnlineUserRenderer;
import javachatclient.Struct.UserStruct;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ubuntu
 */
public class RoomPannel extends javax.swing.JPanel {

    /**
     * Creates new form RoomPannel
     */
    
    /**/
    private DefaultListModel listModel;
    private String sUser;
     
    private boolean checkUser=true;
    
    public int IDROOM;
    public String Name;
    public int status;
    public int isOwner = 0;
    public int indexOfTab;
    public String passROOM="";
        
    public HashSet<UserStruct> userRoomList = new HashSet<UserStruct>();
    /*multi input*/
    private JFrame frame;
    private JPanel pane;
    private JTextField nameROOMField,nameUserField;
    private JPasswordField passROOMField,passCURField,passNEWField;
    private String nameROOM="";
    
    
     /**
     * End line
     */
    
    public RoomPannel(String Name, int IDROOM, int status) {
        initComponents();
        txtContent.setEditable(false);
        this.Name = Name;
        this.IDROOM = IDROOM;
        this.status = status;
        /*SET ROOMNAME*/
        
//        String nameRoom = "<html><span style='font-size:20px'>"+Name+"</span></html>";
//        lbRoomName.setText(nameRoom);
        
        /**/
        btnAddUser.setEnabled(false);
        btnKickUser.setEnabled(false);
        btnTerminate.setEnabled(false);
        btnRePass.setEnabled(false);
        
         /**/
        listUser.setModel(new DefaultListModel());
        listModel = new DefaultListModel();
        /**/
        String Path = System.getProperty("user.dir");
        ImageIcon imgThisImg = new ImageIcon(Path + "/images/plus.png");
        Image img = imgThisImg.getImage();
        Image resizedImg = img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        imgThisImg = new ImageIcon(resizedImg);
        btnAddUser.setIcon(imgThisImg);
        /*icon kick*/
        ImageIcon imgThisImgKick = new ImageIcon(Path + "/images/kick.png");
        Image imgKick = imgThisImgKick.getImage();
        Image resizedImgKick = imgKick.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        imgThisImgKick = new ImageIcon(resizedImgKick);
        btnKickUser.setIcon(imgThisImgKick);
        /*icon Delete*/
        ImageIcon imgThisImgDelete = new ImageIcon(Path + "/images/delete.png");
        Image imgDelete = imgThisImgDelete.getImage();
        Image resizedImgDelete = imgDelete.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        imgThisImgDelete = new ImageIcon(resizedImgDelete);
        btnTerminate.setIcon(imgThisImgDelete);
        /*icon Refresh*/ 
        ImageIcon imgThisImgRe = new ImageIcon(Path + "/images/refresh.png");
        Image imgRe = imgThisImgRe.getImage();
        Image resizedImgRe = imgRe.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        imgThisImgRe = new ImageIcon(resizedImgRe);
        btnRefresh.setIcon(imgThisImgRe);
        /*icon Refresh*/
        ImageIcon imgThisImgRePass = new ImageIcon(Path + "/images/pass.png");
        Image imgRePass = imgThisImgRePass.getImage();
        Image resizedImgRePass = imgRePass.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        imgThisImgRePass = new ImageIcon(resizedImgRePass);
        btnRePass.setIcon(imgThisImgRePass);
        /*hint*/
        btnAddUser.setToolTipText("Click button if you want to Add Specific User in this Room ");
        btnKickUser.setToolTipText("Click button if you want to Kick Specific User in this Room ");
        btnRePass.setToolTipText("Click button if you want to Change pass in this Room ");
        btnTerminate.setToolTipText("Click button if you want to Delete this Room ");
        btnRefresh.setToolTipText("Click button if you want to refresh this curent User in this Room ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHostName = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnKickUser = new javax.swing.JButton();
        txtChat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        btnTerminate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnRePass = new javax.swing.JButton();

        lbHostName.setText("HOST");

        btnAddUser.setText("AddUser");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnKickUser.setText("KickUser");
        btnKickUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKickUserActionPerformed(evt);
            }
        });

        txtChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChatActionPerformed(evt);
            }
        });
        txtChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChatKeyPressed(evt);
            }
        });

        jLabel1.setText("List");

        jScrollPane2.setViewportView(listUser);

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        btnTerminate.setText("Terminate");
        btnTerminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnRePass.setText("Change Room's Pass");
        btnRePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbHostName)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(268, 268, 268))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRePass)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddUser)
                                    .addComponent(btnKickUser))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTerminate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHostName)
                            .addComponent(btnRePass))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddUser)
                            .addComponent(btnTerminate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKickUser)
                            .addComponent(btnRefresh))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void AddChatMess(String User, String Mess){
        if (!GlobalStatic.myUserName.equals(User)){
            txtContent.append(User + ": " + Mess + "\n");
            txtContent.setCaretPosition(txtContent.getDocument().getLength());
        }
    }
    
    public void RefreshClick(){
        btnRefresh.doClick();
    }
    public void SetPassRoom(String passRoom){
        this.passROOM = passRoom;
    }
    
    public void SetButton()
    {
        if(this.isOwner == 0)
        {
            try {
                btnAddUser.setEnabled(false);
                btnKickUser.setEnabled(false);
                btnTerminate.setEnabled(false);
                btnRePass.setEnabled(false);
                
            } catch (Exception e) {
            }
        }
        else
        {
            try {
                btnAddUser.setEnabled(true);
                btnKickUser.setEnabled(true);
                btnTerminate.setEnabled(true);
                btnRePass.setEnabled(true);
                
            } catch (Exception e) {
            }
        }
    }
    
    public void ReloadList(){
        System.out.println("GUIPannel.RoomPannel.ReloadList() 1");
        listModel.removeAllElements();
        System.out.println("GUIPannel.RoomPannel.ReloadList() 2");
        for (UserStruct uS: userRoomList){
            try {
                System.out.println("i day:" + uS.userName);
                //System.err.println(sP.onlineUser.elementAt(k).userName);
                listModel.addElement(uS);
                
            } catch (Exception e) {

                System.out.println("GUIPannel.RoomPannel.ReloadList()"+ e);

            }
        }
        
            if(true)
            {
                listUser.setModel(listModel);
            }
                            
        //Now render Jlist
        listUser.setCellRenderer(new OnlineUserRenderer());
    }
    
    public void ClearUserList(){
        userRoomList.clear();
        
    }
    
    public int AddToList(String userName){

        for (UserStruct uS: userRoomList){
            if (uS.userName.equals(userName)){
                try {
                    ReloadList();
                } catch (Exception e) {
                }
                
                return 1;
            }
        }
        this.userRoomList.add(new UserStruct(userName, 1));
        System.out.println("ADDED one new man to room" + userName);
        try{
            ReloadList();
        } catch (Exception e){
            
        }

        return 1;
    }
    
    public int RemoveFromList(String userName){
        for (UserStruct uS: userRoomList){
            if (uS.userName.equals(userName)){
                userRoomList.remove(uS);
                ReloadList();
                return 1;
            }
        }
        
        return 1;
    }
    
    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:

        int mc = JOptionPane.INFORMATION_MESSAGE;
        sUser = JOptionPane.showInputDialog (null, "Type User", "Add USer to Private Chat", mc);
        GlobalStatic.clientThread.AddFriendToRoom(this.IDROOM,sUser); //sUser
        
        System.err.println("INVITED MR/MRS  "+sUser+ "INTO ROOM ID "+ IDROOM);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnKickUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKickUserActionPerformed
        // TODO add your handling code here:
        int mc = JOptionPane.INFORMATION_MESSAGE;
        sUser = JOptionPane.showInputDialog (null, "Type User", "Kick User ", mc);
        System.out.println("IDROOM WHEN KICK:" + this.IDROOM);
        GlobalStatic.clientThread.RemoveFriendFromRoom(sUser, IDROOM, "");

    }//GEN-LAST:event_btnKickUserActionPerformed

    private void txtChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChatActionPerformed

    private void txtChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChatKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            System.out.println("ID KHI SEND: " + this.IDROOM);
            txtContent.append(txtChat.getText() + "\n");
            txtContent.setCaretPosition(txtContent.getDocument().getLength());
            GlobalStatic.clientThread.SendMsgToRoom(this.IDROOM,txtChat.getText());
            txtChat.setText("");

        }

    }//GEN-LAST:event_txtChatKeyPressed

    private void btnTerminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminateActionPerformed
        // TODO add your handling code here:
        int mc = JOptionPane.INFORMATION_MESSAGE;
        int iTerminate = JOptionPane.showConfirmDialog(null, "WANT TO TERMINATE??", "OWNER COMMAND",JOptionPane.YES_NO_OPTION     , mc);
        if(iTerminate==JOptionPane.YES_OPTION)
        {
            System.out.println("TERMINATE ROOM : "+ this.Name +" WITH ROOM ID:  " + this.IDROOM);
            GlobalStatic.clientThread.TerminateRoom(this.IDROOM);
        }
        else
        {
            System.out.println("CANCEL TERMINATE IN ROOM : "+ this.Name +" WITH ROOM ID:  " + this.IDROOM);
        }
    }//GEN-LAST:event_btnTerminateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        GlobalStatic.clientThread.ReFreshROOMGUI(this.IDROOM);
        System.err.println("REQUEST SERVER TO RECEIVED A LIST ON ROOM ID "+this.IDROOM);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRePassActionPerformed
        // TODO add your handling code here:
        {
            /*GET MULTI INPUT */
            pane = new JPanel();
            pane.setLayout(new GridLayout(0, 2, 2, 2));
            passCURField = new JPasswordField(29);
            passNEWField = new JPasswordField(29);
            pane.add(new JLabel("Fill current Password"));
            pane.add(passCURField);
            pane.add(new JLabel("Set NEW Password"));
            pane.add(passNEWField);

            int option = JOptionPane.showConfirmDialog(frame, pane, "Please FILL ALL", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (option == JOptionPane.OK_OPTION) {

                String passCUR = passCURField.getText();
                String passNEW = passNEWField.getText();
                if(passCUR.equals(GlobalStatic.passRoomTemp)){
                    GlobalStatic.clientThread.RePassRoom(this.IDROOM,passNEW);
                }
                else{
                    int mcServer = JOptionPane.ERROR_MESSAGE;
                    JOptionPane.showMessageDialog (null, "PASSWORD NOT MATCH", "ERROR", mcServer);
                    System.err.println("NOT ACCESS ");
                }
            }
            else{
                System.err.println("Cancel action");
            }
        }
    }//GEN-LAST:event_btnRePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnKickUser;
    private javax.swing.JButton btnRePass;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTerminate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHostName;
    private javax.swing.JList<String> listUser;
    private javax.swing.JTextField txtChat;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
