/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPannel;

import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javachatclient.GlobalStatic;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import jdk.nashorn.internal.objects.Global;

/**
 *
 * @author ubuntu
 */
public class SignInPannel extends javax.swing.JPanel {

    /**
     * Creates new form SignInPannel
     */
    
    
    
    
    String sUser, sPass;
    public int connectStatus = 0;
    
    public SignInPannel() {
        initComponents();
        String Path = System.getProperty("user.dir");
        ImageIcon imgThisImg = new ImageIcon(Path + "/images/refresh.png");
        Image img = imgThisImg.getImage();
        Image resizedImg = img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        imgThisImg = new ImageIcon(resizedImg);
        btnReconnect.setIcon(imgThisImg);
        btnReconnect.setEnabled(false);
        btnReconnect.setToolTipText("Click button if auto reconnect fail ");
        btnSignIn.setToolTipText("Click button to login ");
        btnSignUp.setToolTipText("Click button if not account to login");
    }
    
    public void showReconBtn(){
        btnReconnect.setEnabled(true);
    }
    
    public void HideReconBtn(){
        btnReconnect.setEnabled(false);
    }
    
    
    public void ClickRecon(){
        btnReconnect.doClick();
    }
    public void ClearText(){
        txtUser.setText("");
        txtPassF.setText("");
    }

    public void SetConnectStatus(int status){
        if (status == 1){
            GlobalStatic.myUserName = sUser;
            GlobalStatic.myPass = sPass;
            int mcServer = JOptionPane.INFORMATION_MESSAGE;
            String notify = "<html>Welcome MR/MS <span style='color:green'>"+GlobalStatic.myUserName+"</span> come back</html>";
            JOptionPane.showMessageDialog (null, notify, "Have A Nice Day", mcServer); 
            
            
        }
        else if (status == 0){
            int mc = JOptionPane.WARNING_MESSAGE;
            JOptionPane.showMessageDialog (null, "Sign In Fail", "Warning", mc);
        }
        this.connectStatus = status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassF = new javax.swing.JPasswordField();
        btnReconnect = new javax.swing.JButton();

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel2.setText("Need an account? Register now!!!");

        jLabel1.setText("Powered by VERMOUNTH");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("WELCOME BACK");

        txtPassF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassFActionPerformed(evt);
            }
        });
        txtPassF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassFKeyPressed(evt);
            }
        });

        btnReconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPassF, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnReconnect))
                        .addGap(18, 18, 18)))
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(txtPassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        sUser = txtUser.getText();
        //sPass=txtPass.getText();
        sPass = txtPassF.getText();
        if(sUser.equals(""))
        {        
            int mc = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog (null, "Blank User", "Sign In Fail", mc);
        }  
        else if(sPass.equals("")){
            int mc = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog (null, "Blank Password", "Sign In Fail", mc);
        }
                else{
                        if(GlobalStatic.connectionStatus == true)
                        {

                            GlobalStatic.clientThread.SignIn(sUser, sPass);
                        }
                        else
                        {
                            int mc = JOptionPane.ERROR_MESSAGE;
                            JOptionPane.showMessageDialog (null, "Sign In Fail", "Can not connect to Server", mc);
                        }
        }
        
        

    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:

        /* ADD FUCNTION SIGN UP */
        //GlobalStatic.signupPannel.setVisible(true);
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        GlobalStatic.signinPannel.setVisible(false);
        topFrame.add(GlobalStatic.signupPannel);
        GlobalStatic.signupPannel.setVisible(true);
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnReconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconnectActionPerformed
        try {
            System.out.println("Reconnect is clicked");
            btnReconnect.setEnabled(false);
            Thread.sleep(1000);
            GlobalStatic.clientThread.timeToRecon = 0;
            GlobalStatic.clientThread.InitThreadRecon();
            //GlobalStatic.clientThread.StartReadThread();
        } catch (InterruptedException ex) {   System.out.println("catch");     }
    }//GEN-LAST:event_btnReconnectActionPerformed

    private void txtPassFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassFActionPerformed

    private void txtPassFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassFKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            sUser = txtUser.getText();
        //sPass=txtPass.getText();
        sPass = txtPassF.getText();
        if(sUser.equals(""))
        {        
            int mc = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog (null, "Blank User", "Sign In Fail", mc);
        }  
        else if(sPass.equals("")){
            int mc = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog (null, "Blank Password", "Sign In Fail", mc);
        }
                else{
                        if(GlobalStatic.connectionStatus == true)
                        {

                            GlobalStatic.clientThread.SignIn(sUser, sPass);
                        }
                        else
                        {
                            int mc = JOptionPane.ERROR_MESSAGE;
                            JOptionPane.showMessageDialog (null, "Sign In Fail", "Can not connect to Server", mc);
                        }
        }
        }
        
    }//GEN-LAST:event_txtPassFKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReconnect;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassF;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
