#pragma once
#include <iostream>
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <net/if.h>
#include <ifaddrs.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <unistd.h>
#include <thread>
#include <set>
#include <sys/poll.h>
#include <sys/ioctl.h>
#include <mutex>
#include <fstream>
#include "List.h"
#include <vector>
#include <stack>
using namespace std;
